/**
 * Master Agricultural Location Data for Farmer CRM
 * Structured hierarchy: State -> District -> Taluka (Thaluka) -> Village with standard pin codes.
 * Tamil Nadu, Andhra Pradesh and Telangana districts, taluks and villages follow the Local Government
 * Directory; villages live in <code>-villages.json and are lazy-loaded so they stay out of the main bundle.
 * Karnataka and Kerala carry major agricultural districts only (no village lists).
 */

import { canonicalDistrictKey } from '@grotec/shared';

export interface TalukInfo {
  name: string;
  pincode?: string;
}

export interface DistrictInfo {
  name: string;
  taluks: TalukInfo[];
  defaultPincode?: string;
}

export interface StateInfo {
  name: string;
  code: string;
  districts: DistrictInfo[];
}

export const STATES_DATA: StateInfo[] = [
  {
    name: 'Tamil Nadu',
    code: 'TN',
    districts: [
      {
        name: 'Ariyalur',
        defaultPincode: '621704',
        taluks: [
          { name: 'Andimadam', pincode: '621801' },
          { name: 'Ariyalur', pincode: '621704' },
          { name: 'Sendurai', pincode: '621714' },
          { name: 'Udayarpalayam', pincode: '621804' },
        ],
      },
      {
        name: 'Chengalpattu',
        defaultPincode: '603001',
        taluks: [
          { name: 'Chengalpattu', pincode: '603001' },
          { name: 'Cheyyur', pincode: '603302' },
          { name: 'Maduranthakam', pincode: '603306' },
          { name: 'Pallavaram' },
          { name: 'Tambaram', pincode: '600045' },
          { name: 'Tirukalukundram' },
          { name: 'Tiruporur' },
          { name: 'Vandalur' },
        ],
      },
      {
        name: 'Chennai',
        taluks: [
          { name: 'Alandur' },
          { name: 'Ambattur' },
          { name: 'Aminjikarai' },
          { name: 'Ayanavaram' },
          { name: 'Egmore' },
          { name: 'Guindy' },
          { name: 'Kolathur' },
          { name: 'Maduravoyal' },
          { name: 'Mambalam' },
          { name: 'Mathavaram' },
          { name: 'Mylapore' },
          { name: 'Perambur' },
          { name: 'Purasawalkam' },
          { name: 'Sholinganallur' },
          { name: 'Tiruvottiyur' },
          { name: 'Tondiarpet' },
          { name: 'Velachery' },
        ],
      },
      {
        name: 'Coimbatore',
        defaultPincode: '641001',
        taluks: [
          { name: 'Anaimalai', pincode: '642104' },
          { name: 'Annur', pincode: '641653' },
          { name: 'Coimbatore North', pincode: '641030' },
          { name: 'Coimbatore South', pincode: '641001' },
          { name: 'Kinathukadavu', pincode: '642109' },
          { name: 'Madukkari' },
          { name: 'Mettupalayam', pincode: '641301' },
          { name: 'Perur' },
          { name: 'Pollachi', pincode: '642001' },
          { name: 'Sulur', pincode: '641402' },
          { name: 'Valparai', pincode: '642127' },
        ],
      },
      {
        name: 'Cuddalore',
        defaultPincode: '607001',
        taluks: [
          { name: 'Bhuvanagiri', pincode: '608601' },
          { name: 'Chidambaram', pincode: '608001' },
          { name: 'Cuddalore', pincode: '607001' },
          { name: 'Kattumannarkoil', pincode: '608301' },
          { name: 'Kurinjipadi', pincode: '607302' },
          { name: 'Panruti', pincode: '607106' },
          { name: 'Srimushnam', pincode: '608703' },
          { name: 'Tittakudi' },
          { name: 'Veppur' },
          { name: 'Virudhachalam', pincode: '606001' },
        ],
      },
      {
        name: 'Dharmapuri',
        defaultPincode: '636701',
        taluks: [
          { name: 'Dharmapuri', pincode: '636701' },
          { name: 'Harur', pincode: '636903' },
          { name: 'Karimangalam', pincode: '635111' },
          { name: 'Nallampalli', pincode: '636807' },
          { name: 'Palakkodu' },
          { name: 'Pappireddipatti', pincode: '636905' },
          { name: 'Pennagaram', pincode: '636810' },
        ],
      },
      {
        name: 'Dindigul',
        defaultPincode: '624001',
        taluks: [
          { name: 'Athoor' },
          { name: 'Dindiguleast' },
          { name: 'Dindigulwest' },
          { name: 'Gujiliamparai', pincode: '624703' },
          { name: 'Kodaikanal', pincode: '624101' },
          { name: 'Natham', pincode: '624401' },
          { name: 'Nilakkottai' },
          { name: 'Oddanchatram', pincode: '624619' },
          { name: 'Palani', pincode: '624601' },
          { name: 'Vedasandur', pincode: '624710' },
        ],
      },
      {
        name: 'Erode',
        defaultPincode: '638001',
        taluks: [
          { name: 'Anthiyur', pincode: '638501' },
          { name: 'Bhavani', pincode: '638301' },
          { name: 'Erode', pincode: '638001' },
          { name: 'Gobichettipalayam', pincode: '638452' },
          { name: 'Kodumudi', pincode: '638151' },
          { name: 'Modakkurichi', pincode: '638104' },
          { name: 'Nambiyur' },
          { name: 'Perundurai', pincode: '638052' },
          { name: 'Sathyamangalam', pincode: '638401' },
          { name: 'Thalavadi', pincode: '638461' },
        ],
      },
      {
        name: 'Kallakurichi',
        defaultPincode: '606202',
        taluks: [
          { name: 'Chinnasalem', pincode: '606201' },
          { name: 'Kallakkurichi' },
          { name: 'Kalvarayan Hills' },
          { name: 'Sankarapuram', pincode: '606401' },
          { name: 'Tirukkoyilur' },
          { name: 'Ulundurpettai' },
          { name: 'Vanapuram' },
        ],
      },
      {
        name: 'Kancheepuram',
        defaultPincode: '631501',
        taluks: [
          { name: 'Kancheepuram', pincode: '631501' },
          { name: 'Kundrathur', pincode: '600069' },
          { name: 'Sriperumbudur', pincode: '602105' },
          { name: 'Uthiramerur', pincode: '603406' },
          { name: 'Walajabad', pincode: '631605' },
        ],
      },
      {
        name: 'Kanniyakumari',
        defaultPincode: '629001',
        taluks: [
          { name: 'Agastheeswaram', pincode: '629702' },
          { name: 'Kalkulam', pincode: '629175' },
          { name: 'Killiyoor' },
          { name: 'Thiruvattar', pincode: '629177' },
          { name: 'Thovala' },
          { name: 'Vilavancode', pincode: '629163' },
        ],
      },
      {
        name: 'Karur',
        defaultPincode: '639001',
        taluks: [
          { name: 'Aravakurichi', pincode: '639201' },
          { name: 'Kadavur', pincode: '621311' },
          { name: 'Karur', pincode: '639001' },
          { name: 'Krishnarayapuram', pincode: '639102' },
          { name: 'Kulithalai', pincode: '639104' },
          { name: 'Manmangalam', pincode: '639006' },
          { name: 'Pugalur', pincode: '639113' },
        ],
      },
      {
        name: 'Krishnagiri',
        defaultPincode: '635001',
        taluks: [
          { name: 'Anchetty', pincode: '636815' },
          { name: 'Bargur', pincode: '635104' },
          { name: 'Denkanikottai', pincode: '635107' },
          { name: 'Hosur', pincode: '635109' },
          { name: 'Krishnagiri', pincode: '635001' },
          { name: 'Pochampalli', pincode: '635206' },
          { name: 'Shoolagiri', pincode: '635117' },
          { name: 'Uthangarai', pincode: '635207' },
        ],
      },
      {
        name: 'Madurai',
        defaultPincode: '625001',
        taluks: [
          { name: 'Kalligudi', pincode: '625701' },
          { name: 'Madurai East', pincode: '625020' },
          { name: 'Madurai North', pincode: '625002' },
          { name: 'Madurai South', pincode: '625001' },
          { name: 'Madurai West' },
          { name: 'Melur', pincode: '625106' },
          { name: 'Peraiyur', pincode: '625703' },
          { name: 'Thirumangalam', pincode: '625706' },
          { name: 'Thirupparankundram' },
          { name: 'Usilampatti', pincode: '625532' },
          { name: 'Vadipatti', pincode: '625218' },
        ],
      },
      {
        name: 'Mayiladuthurai',
        defaultPincode: '609001',
        taluks: [
          { name: 'Kuthalam', pincode: '609801' },
          { name: 'Mayiladuthurai', pincode: '609001' },
          { name: 'Sirkali' },
          { name: 'Tharangambadi', pincode: '609305' },
        ],
      },
      {
        name: 'Nagapattinam',
        defaultPincode: '611001',
        taluks: [
          { name: 'Kilvelur', pincode: '611104' },
          { name: 'Nagapattinam', pincode: '611001' },
          { name: 'Thirukkuvalai', pincode: '610205' },
          { name: 'Vedaranyam', pincode: '614810' },
        ],
      },
      {
        name: 'Namakkal',
        defaultPincode: '637001',
        taluks: [
          { name: 'Kolli Hills', pincode: '637411' },
          { name: 'Kumarapalayam', pincode: '638183' },
          { name: 'Mohanur', pincode: '637015' },
          { name: 'Namakkal', pincode: '637001' },
          { name: 'Paramathi-Velur' },
          { name: 'Rasipuram', pincode: '637408' },
          { name: 'Sendamangalam', pincode: '637409' },
          { name: 'Tiruchengode', pincode: '637211' },
        ],
      },
      {
        name: 'Perambalur',
        defaultPincode: '621212',
        taluks: [
          { name: 'Alathur', pincode: '621109' },
          { name: 'Kunnam', pincode: '621708' },
          { name: 'Perambalur', pincode: '621212' },
          { name: 'Veppanthattai', pincode: '621116' },
        ],
      },
      {
        name: 'Pudukkottai',
        defaultPincode: '622001',
        taluks: [
          { name: 'Alangudi', pincode: '622301' },
          { name: 'Aranthangi', pincode: '614616' },
          { name: 'Avudayarkoil' },
          { name: 'Gandarvakkottai', pincode: '613301' },
          { name: 'Iluppur', pincode: '622102' },
          { name: 'Karambakudi' },
          { name: 'Kulathur', pincode: '622504' },
          { name: 'Manamelkudi', pincode: '614620' },
          { name: 'Ponnamaravathi', pincode: '622407' },
          { name: 'Pudukkottai', pincode: '622001' },
          { name: 'Thirumayam', pincode: '622507' },
          { name: 'Viralimalai', pincode: '621316' },
        ],
      },
      {
        name: 'Ramanathapuram',
        defaultPincode: '623501',
        taluks: [
          { name: 'Kadaladi', pincode: '623703' },
          { name: 'Kamuthi', pincode: '623603' },
          { name: 'Kilakarai' },
          { name: 'Mudukulathur', pincode: '623704' },
          { name: 'Paramakudi', pincode: '623707' },
          { name: 'Rajasingamangalam' },
          { name: 'Ramanathapuram', pincode: '623501' },
          { name: 'Rameswaram', pincode: '623526' },
          { name: 'Tiruvadanai', pincode: '623407' },
        ],
      },
      {
        name: 'Ranipet',
        defaultPincode: '632401',
        taluks: [
          { name: 'Arakonam' },
          { name: 'Arcot', pincode: '632503' },
          { name: 'Kalavai', pincode: '632506' },
          { name: 'Nemili', pincode: '631051' },
          { name: 'Sholinghur' },
          { name: 'Wallajah' },
        ],
      },
      {
        name: 'Salem',
        defaultPincode: '636001',
        taluks: [
          { name: 'Attur', pincode: '636102' },
          { name: 'Edappadi', pincode: '637101' },
          { name: 'Gangavalli', pincode: '636105' },
          { name: 'Kadayampatti', pincode: '636351' },
          { name: 'Mettur', pincode: '636401' },
          { name: 'Omalur', pincode: '636455' },
          { name: 'Pethanaickanpalayam' },
          { name: 'Salem', pincode: '636001' },
          { name: 'Salem South', pincode: '636006' },
          { name: 'Salem West', pincode: '636009' },
          { name: 'Sankari', pincode: '637301' },
          { name: 'Thalaivasal' },
          { name: 'Vazhapadi', pincode: '636115' },
          { name: 'Yercaud', pincode: '636601' },
        ],
      },
      {
        name: 'Sivaganga',
        defaultPincode: '630561',
        taluks: [
          { name: 'Devakottai', pincode: '630302' },
          { name: 'Ilayangudi', pincode: '630702' },
          { name: 'Kalaiyarkoil' },
          { name: 'Karaikkudi' },
          { name: 'Manamadurai', pincode: '630606' },
          { name: 'Singampunari', pincode: '630502' },
          { name: 'Sivaganga', pincode: '630561' },
          { name: 'Thiruppathur' },
          { name: 'Thiruppuvanam' },
        ],
      },
      {
        name: 'Tenkasi',
        defaultPincode: '627811',
        taluks: [
          { name: 'Alangulam', pincode: '627851' },
          { name: 'Kadayanallur', pincode: '627751' },
          { name: 'Sankarankoil' },
          { name: 'Shenkottai' },
          { name: 'Sivagiri', pincode: '627757' },
          { name: 'Tenkasi', pincode: '627811' },
          { name: 'Tiruvengadam' },
          { name: 'Veerakeralamputhur', pincode: '627861' },
        ],
      },
      {
        name: 'Thanjavur',
        defaultPincode: '613001',
        taluks: [
          { name: 'Budalur', pincode: '613602' },
          { name: 'Kumbakonam', pincode: '612001' },
          { name: 'Orathanadu', pincode: '614625' },
          { name: 'Papanasam', pincode: '614205' },
          { name: 'Pattukkottai', pincode: '614601' },
          { name: 'Peravurani', pincode: '614804' },
          { name: 'Thanjavur', pincode: '613001' },
          { name: 'Thiruvaiyaru', pincode: '613204' },
          { name: 'Thiruvidaimarudur', pincode: '612104' },
          { name: 'Thiruvonam' },
        ],
      },
      {
        name: 'The Nilgiris',
        defaultPincode: '643001',
        taluks: [
          { name: 'Coonoor', pincode: '643101' },
          { name: 'Gudalur', pincode: '643212' },
          { name: 'Kotagiri', pincode: '643217' },
          { name: 'Kundah', pincode: '643219' },
          { name: 'Panthalur' },
          { name: 'Udhagamandalam', pincode: '643001' },
        ],
      },
      {
        name: 'Theni',
        defaultPincode: '625531',
        taluks: [
          { name: 'Andipatti', pincode: '625512' },
          { name: 'Bodinayakanur', pincode: '625513' },
          { name: 'Periyakulam', pincode: '625601' },
          { name: 'Theni', pincode: '625531' },
          { name: 'Uthamapalayam', pincode: '625533' },
        ],
      },
      {
        name: 'Thiruvallur',
        defaultPincode: '602001',
        taluks: [
          { name: 'Avadi' },
          { name: 'Gummidipoondi', pincode: '601201' },
          { name: 'Pallipattu' },
          { name: 'Ponneri', pincode: '601204' },
          { name: 'Poonamallee', pincode: '600056' },
          { name: 'R K Pet' },
          { name: 'Thiruvallur' },
          { name: 'Tiruttani', pincode: '631209' },
          { name: 'Uthukkottai', pincode: '602026' },
        ],
      },
      {
        name: 'Thiruvarur',
        defaultPincode: '610001',
        taluks: [
          { name: 'Koothanallur' },
          { name: 'Kudavasal', pincode: '612601' },
          { name: 'Mannargudi', pincode: '614001' },
          { name: 'Muthupettai' },
          { name: 'Nannilam', pincode: '610105' },
          { name: 'Needamangalam', pincode: '614404' },
          { name: 'Thiruthuraipoondi', pincode: '614713' },
          { name: 'Thiruvarur' },
          { name: 'Valangaiman', pincode: '612804' },
        ],
      },
      {
        name: 'Thoothukkudi',
        defaultPincode: '628001',
        taluks: [
          { name: 'Eral', pincode: '628801' },
          { name: 'Ettayapuram' },
          { name: 'Kayathar', pincode: '628952' },
          { name: 'Kovilpatti', pincode: '628501' },
          { name: 'Ottapidaram', pincode: '628401' },
          { name: 'Sathankulam', pincode: '628704' },
          { name: 'Srivaikuntam', pincode: '628601' },
          { name: 'Thoothukkudi' },
          { name: 'Tiruchendur', pincode: '628215' },
          { name: 'Vilathikulam', pincode: '628907' },
        ],
      },
      {
        name: 'Tiruchirappalli',
        defaultPincode: '620001',
        taluks: [
          { name: 'Lalgudi', pincode: '621601' },
          { name: 'Manachanallur', pincode: '621005' },
          { name: 'Manapparai', pincode: '621306' },
          { name: 'Marungapuri', pincode: '621314' },
          { name: 'Musiri', pincode: '621211' },
          { name: 'Srirangam', pincode: '620006' },
          { name: 'Thiruverumbur' },
          { name: 'Thottiyam', pincode: '621215' },
          { name: 'Thuraiyur', pincode: '621010' },
          { name: 'Tiruchirappalli East', pincode: '620001' },
          { name: 'Tiruchirappalli West', pincode: '620002' },
        ],
      },
      {
        name: 'Tirunelveli',
        defaultPincode: '627001',
        taluks: [
          { name: 'Ambasamudram', pincode: '627401' },
          { name: 'Cheranmahadevi', pincode: '627414' },
          { name: 'Manur', pincode: '627201' },
          { name: 'Nanguneri', pincode: '627108' },
          { name: 'Palayamkottai', pincode: '627002' },
          { name: 'Radhapuram', pincode: '627111' },
          { name: 'Tirunelveli', pincode: '627001' },
          { name: 'Tisayanvilai', pincode: '627657' },
        ],
      },
      {
        name: 'Tirupathur',
        defaultPincode: '635601',
        taluks: [
          { name: 'Ambur', pincode: '635802' },
          { name: 'Natrampalli', pincode: '635852' },
          { name: 'Tirupathur', pincode: '635601' },
          { name: 'Vaniyambadi', pincode: '635751' },
        ],
      },
      {
        name: 'Tiruppur',
        defaultPincode: '641601',
        taluks: [
          { name: 'Avinashi', pincode: '641654' },
          { name: 'Dharapuram', pincode: '638656' },
          { name: 'Kangeyam', pincode: '638701' },
          { name: 'Madathukulam', pincode: '642113' },
          { name: 'Palladam' },
          { name: 'Tiruppurnorth' },
          { name: 'Tiruppursouth' },
          { name: 'Udumalaipettai', pincode: '642126' },
          { name: 'Uthukuli', pincode: '638751' },
        ],
      },
      {
        name: 'Tiruvannamalai',
        defaultPincode: '606601',
        taluks: [
          { name: 'Arani', pincode: '632301' },
          { name: 'Chengam', pincode: '606701' },
          { name: 'Chetpet', pincode: '606801' },
          { name: 'Cheyyar', pincode: '604407' },
          { name: 'Jamunamarathoor' },
          { name: 'Kalasapakkam', pincode: '606751' },
          { name: 'Kilpennathur', pincode: '604601' },
          { name: 'Polur', pincode: '606803' },
          { name: 'Thandrampet' },
          { name: 'Tiruvannamalai', pincode: '606601' },
          { name: 'Vandavasi', pincode: '604408' },
          { name: 'Vembakkam' },
        ],
      },
      {
        name: 'Vellore',
        defaultPincode: '632001',
        taluks: [
          { name: 'Anaicut', pincode: '632101' },
          { name: 'Gudiyatham', pincode: '632602' },
          { name: 'K V Kuppam' },
          { name: 'Katpadi', pincode: '632007' },
          { name: 'Pernambut', pincode: '635810' },
          { name: 'Vellore', pincode: '632001' },
        ],
      },
      {
        name: 'Viluppuram',
        defaultPincode: '605602',
        taluks: [
          { name: 'Gingee', pincode: '604202' },
          { name: 'Kandachipuram' },
          { name: 'Marakanam' },
          { name: 'Melmalaiyanur' },
          { name: 'Thiruvennainallur' },
          { name: 'Tindivanam', pincode: '604001' },
          { name: 'Vanur', pincode: '605109' },
          { name: 'Vikravandi', pincode: '605652' },
          { name: 'Viluppuram', pincode: '605602' },
        ],
      },
      {
        name: 'Virudhunagar',
        defaultPincode: '626001',
        taluks: [
          { name: 'Aruppukkottai', pincode: '626101' },
          { name: 'Kariapatti', pincode: '626106' },
          { name: 'Rajapalayam', pincode: '626117' },
          { name: 'Sattur', pincode: '626203' },
          { name: 'Sivakasi', pincode: '626123' },
          { name: 'Srivilliputhur', pincode: '626125' },
          { name: 'Tiruchuli', pincode: '626129' },
          { name: 'Vembakottai', pincode: '626131' },
          { name: 'Virudhunagar', pincode: '626001' },
          { name: 'Watrap', pincode: '626132' },
        ],
      },
    ],
  },
  {
    name: 'Karnataka',
    code: 'KA',
    districts: [
      {
        name: 'Kolar',
        defaultPincode: '563101',
        taluks: [
          { name: 'Kolar', pincode: '563101' },
          { name: 'Bangarapet', pincode: '563114' },
          { name: 'Malur', pincode: '563130' },
          { name: 'Mulbagal', pincode: '563131' },
          { name: 'Srinivaspur', pincode: '563135' },
        ],
      },
      {
        name: 'Chikkaballapur',
        defaultPincode: '562101',
        taluks: [
          { name: 'Chikkaballapur', pincode: '562101' },
          { name: 'Bagepalli', pincode: '561207' },
          { name: 'Chintamani', pincode: '563125' },
          { name: 'Gauribidanur', pincode: '561208' },
          { name: 'Sidlaghatta', pincode: '562105' },
        ],
      },
      {
        name: 'Bengaluru Rural',
        defaultPincode: '562110',
        taluks: [
          { name: 'Devanahalli', pincode: '562110' },
          { name: 'Doddaballapura', pincode: '561203' },
          { name: 'Hoskote', pincode: '562114' },
          { name: 'Nelamangala', pincode: '562123' },
        ],
      },
      {
        name: 'Mysuru',
        defaultPincode: '570001',
        taluks: [
          { name: 'Mysuru', pincode: '570001' },
          { name: 'Hunsur', pincode: '571105' },
          { name: 'Nanjangud', pincode: '571301' },
          { name: 'T. Narasipura', pincode: '571124' },
          { name: 'Piriyapatna', pincode: '571107' },
          { name: 'Heggadadevankote', pincode: '571114' },
          { name: 'Krishnarajanagara', pincode: '571602' },
        ],
      },
      {
        name: 'Mandya',
        defaultPincode: '571401',
        taluks: [
          { name: 'Mandya', pincode: '571401' },
          { name: 'Maddur', pincode: '571428' },
          { name: 'Malavalli', pincode: '571430' },
          { name: 'Pandavapura', pincode: '571434' },
          { name: 'Nagamangala', pincode: '571432' },
          { name: 'Krishnarajpet', pincode: '571426' },
          { name: 'Srirangapatna', pincode: '571438' },
        ],
      },
      {
        name: 'Tumakuru',
        defaultPincode: '572101',
        taluks: [
          { name: 'Tumakuru', pincode: '572101' },
          { name: 'Tiptur', pincode: '572201' },
          { name: 'Chiknayakanhalli', pincode: '572214' },
          { name: 'Gubbi', pincode: '572216' },
          { name: 'Kunigal', pincode: '572130' },
          { name: 'Madhugiri', pincode: '572132' },
          { name: 'Sira', pincode: '572137' },
        ],
      },
      {
        name: 'Hassan',
        defaultPincode: '573201',
        taluks: [
          { name: 'Hassan', pincode: '573201' },
          { name: 'Arsikere', pincode: '573103' },
          { name: 'Channarayapatna', pincode: '573116' },
          { name: 'Holenarasipur', pincode: '573211' },
          { name: 'Belur', pincode: '573115' },
          { name: 'Sakleshpur', pincode: '573134' },
        ],
      },
    ],
  },
  {
    name: 'Andhra Pradesh',
    code: 'AP',
    districts: [
      {
        name: 'Alluri Sitharama Raju',
        taluks: [
          { name: 'Ananthagiri' },
          { name: 'Araku Valley' },
          { name: 'Chinthapalli' },
          { name: 'Dumbriguda' },
          { name: 'G.Madugula' },
          { name: 'Gudem Kotha Veedhi' },
          { name: 'Hukumpeta' },
          { name: 'Koyyuru' },
          { name: 'Munchingi Puttu' },
          { name: 'Paderu' },
          { name: 'Peda Bayalu' },
        ],
      },
      {
        name: 'Anakapalli',
        taluks: [
          { name: 'Anakapalli' },
          { name: 'Atchuthapuram' },
          { name: 'Butchayyapeta' },
          { name: 'Cheedikada' },
          { name: 'Chodavaram' },
          { name: 'Devarapalli' },
          { name: 'Golugonda' },
          { name: 'K.Kotapadu' },
          { name: 'Kasimkota' },
          { name: 'Kotauratla' },
          { name: 'Madugula' },
          { name: 'Makavarapalem' },
          { name: 'Munagapaka' },
          { name: 'Nakkapalli' },
          { name: 'Narsipatnam' },
          { name: 'Nathavaram' },
          { name: 'Paravada' },
          { name: 'Payakaraopeta' },
          { name: 'Rambilli' },
          { name: 'Ravikamatham' },
          { name: 'Rolugunta' },
          { name: 'S.Rayavaram' },
          { name: 'Sabbavaram' },
          { name: 'Yelamanchili' },
        ],
      },
      {
        name: 'Ananthapuramu',
        defaultPincode: '515001',
        taluks: [
          { name: 'Anantapur Rural' },
          { name: 'Anantapur Urban' },
          { name: 'Atmakur' },
          { name: 'Beluguppa' },
          { name: 'Bommanahal' },
          { name: 'Brahmasamudram' },
          { name: 'Bukkaraya Samudram' },
          { name: 'D.Hirehal' },
          { name: 'Garladinne' },
          { name: 'Gooty' },
          { name: 'Gummagatta' },
          { name: 'Guntakal', pincode: '515801' },
          { name: 'Kalyanadurg' },
          { name: 'Kambadur' },
          { name: 'Kanekal' },
          { name: 'Kudair' },
          { name: 'Kundurpi' },
          { name: 'Narpala' },
          { name: 'Pamidi' },
          { name: 'Peddapappur' },
          { name: 'Peddavaduguru' },
          { name: 'Putlur' },
          { name: 'Rapthadu' },
          { name: 'Rayadurg' },
          { name: 'Settur' },
          { name: 'Singanamala' },
          { name: 'Tadipatri', pincode: '515411' },
          { name: 'Uravakonda' },
          { name: 'Vajrakarur' },
          { name: 'Vidapanakal' },
          { name: 'Yadiki' },
          { name: 'Yellanur' },
        ],
      },
      {
        name: 'Annamayya',
        defaultPincode: '516269',
        taluks: [
          { name: 'Beerongi Kothakota' },
          { name: 'Chinnamandem' },
          { name: 'Chowdepalle' },
          { name: 'Galiveedu' },
          { name: 'Gurramkonda' },
          { name: 'Kalakada' },
          { name: 'Kalikiri' },
          { name: 'Kambhamvaripalle' },
          { name: 'Kurabalakota' },
          { name: 'Lakkireddipalli' },
          { name: 'Madanapalle', pincode: '517325' },
          { name: 'Mulakalacheruvu' },
          { name: 'Nimmanapalle' },
          { name: 'Pedda Thippasamudram' },
          { name: 'Peddamandyam' },
          { name: 'Pileru', pincode: '517214' },
          { name: 'Punganuru' },
          { name: 'Ramapuram' },
          { name: 'Ramasamudram' },
          { name: 'Rayachoti', pincode: '516269' },
          { name: 'Sambepalle' },
          { name: 'Sodam' },
          { name: 'Somala' },
          { name: 'Thamballapalle' },
          { name: 'Valmikipuram' },
        ],
      },
      {
        name: 'Bapatla',
        taluks: [
          { name: 'Amarthalur' },
          { name: 'Bapatla' },
          { name: 'Bhattiprolu' },
          { name: 'Cherukupalli' },
          { name: 'Chinaganjam' },
          { name: 'Chirala' },
          { name: 'Inkollu' },
          { name: 'Karamchedu' },
          { name: 'Karlapalem' },
          { name: 'Kolluru' },
          { name: 'Martur' },
          { name: 'Nagaram' },
          { name: 'Nizampatnam' },
          { name: 'Parchur' },
          { name: 'Pittalavanipalem' },
          { name: 'Repalle' },
          { name: 'Tsunduru' },
          { name: 'Vemuru' },
          { name: 'Vetapalem' },
          { name: 'Yeddana Pudi' },
        ],
      },
      {
        name: 'Chittoor',
        defaultPincode: '517001',
        taluks: [
          { name: 'Baireddipalle' },
          { name: 'Bangarupalem', pincode: '517416' },
          { name: 'Chittoor Rural' },
          { name: 'Chittoor Urban' },
          { name: 'Gangadhara Nellore' },
          { name: 'Gangavaram' },
          { name: 'Gudipala' },
          { name: 'Gudupalle' },
          { name: 'Irala' },
          { name: 'Karvetinagar' },
          { name: 'Kuppam', pincode: '517425' },
          { name: 'Nagari', pincode: '517590' },
          { name: 'Nindra' },
          { name: 'Palamaner', pincode: '517408' },
          { name: 'Palasamudram' },
          { name: 'Peddapanjani' },
          { name: 'Penumur' },
          { name: 'Pulicherla' },
          { name: 'Puthalapattu' },
          { name: 'Ramakuppam' },
          { name: 'Rompicherla' },
          { name: 'Santhipuram' },
          { name: 'Srirangarajapuram' },
          { name: 'Thavanampalle' },
          { name: 'Vedurukuppam' },
          { name: 'Venkatagirikota' },
          { name: 'Vijayapuram' },
          { name: 'Yadamarri' },
        ],
      },
      {
        name: 'Dr. B.R. Ambedkar Konaseema',
        taluks: [
          { name: 'Ainavilli' },
          { name: 'Alamuru' },
          { name: 'Allavaram' },
          { name: 'Amalapuram' },
          { name: 'Ambajipeta' },
          { name: 'Atreyapuram' },
          { name: 'I. Polavaram' },
          { name: 'K Gangavaram' },
          { name: 'Katrenikona' },
          { name: 'Kothapeta' },
          { name: 'Malikipuram' },
          { name: 'Mamidikuduru' },
          { name: 'Mummidivaram' },
          { name: 'P.Gannavaram' },
          { name: 'Ramachandrapuram' },
          { name: 'Ravulapalem' },
          { name: 'Razole' },
          { name: 'Sakhinetipalli' },
          { name: 'Uppalaguptam' },
        ],
      },
      {
        name: 'East Godavari',
        taluks: [
          { name: 'Anaparthi' },
          { name: 'Biccavolu' },
          { name: 'Chagallu' },
          { name: 'Devarapalle' },
          { name: 'Gokavaram' },
          { name: 'Gopalapuram' },
          { name: 'Kadiam' },
          { name: 'Kapileswarapuram' },
          { name: 'Korukonda' },
          { name: 'Kovvur' },
          { name: 'Mandapeta' },
          { name: 'Nallajerla' },
          { name: 'Nidadavole' },
          { name: 'Peravali' },
          { name: 'Rajamahendravaram Rural' },
          { name: 'Rajamahendravaram Urban Rajamahendravaram' },
          { name: 'Rajanagaram' },
          { name: 'Rangampeta' },
          { name: 'Rayavaram' },
          { name: 'Seethanagaram' },
          { name: 'Tallapudi' },
          { name: 'Undrajavaram' },
        ],
      },
      {
        name: 'Eluru',
        taluks: [
          { name: 'Agiripalli' },
          { name: 'Bheemadole' },
          { name: 'Buttayagudem' },
          { name: 'Chatrai' },
          { name: 'Chintalapudi' },
          { name: 'Denduluru' },
          { name: 'Dwarakatirumala' },
          { name: 'Eluru Rural' },
          { name: 'Eluru Urban' },
          { name: 'Jangareddigudem' },
          { name: 'Jeelugu Milli' },
          { name: 'Kaikaluru' },
          { name: 'Kalidindi' },
          { name: 'Kamavarapukota' },
          { name: 'Koyyalagudem' },
          { name: 'Kukunoor' },
          { name: 'Lingapalem' },
          { name: 'Mandavalli' },
          { name: 'Mudinepalle' },
          { name: 'Musunuru' },
          { name: 'Nidamarru' },
          { name: 'Nuzividu' },
          { name: 'Pedapadu' },
          { name: 'Pedavegi' },
          { name: 'Polavaram' },
          { name: 'T.Narasapuram' },
          { name: 'Unguturu' },
          { name: 'Velairpadu' },
        ],
      },
      {
        name: 'Guntur',
        defaultPincode: '522001',
        taluks: [
          { name: 'Chebrolu' },
          { name: 'Duggirala' },
          { name: 'Guntur East' },
          { name: 'Guntur West' },
          { name: 'Kakumanu' },
          { name: 'Kollipara' },
          { name: 'Mangalagiri', pincode: '522503' },
          { name: 'Medikonduru' },
          { name: 'Pedakakani' },
          { name: 'Pedanandipadu' },
          { name: 'Phirangipuram' },
          { name: 'Ponnur', pincode: '522124' },
          { name: 'Prathipadu' },
          { name: 'Tadepalli' },
          { name: 'Tadikonda' },
          { name: 'Tenali', pincode: '522201' },
          { name: 'Thulluru' },
          { name: 'Vatticherukuru' },
        ],
      },
      {
        name: 'Kakinada',
        taluks: [
          { name: 'Gandepalli' },
          { name: 'Gollaprolu' },
          { name: 'Jaggampeta' },
          { name: 'Kajuluru' },
          { name: 'Kakinada (Rural)' },
          { name: 'Kakinada (Urban)' },
          { name: 'Karapa' },
          { name: 'Kirlampudi' },
          { name: 'Kotananduru' },
          { name: 'Pedapudi' },
          { name: 'Peddapuram' },
          { name: 'Pithapuram' },
          { name: 'Prathipadu' },
          { name: 'Rowthulapudi' },
          { name: 'Samalkota' },
          { name: 'Sankhavaram' },
          { name: 'Tallarevu' },
          { name: 'Thondangi' },
          { name: 'Tuni' },
          { name: 'U.Kothapalli' },
          { name: 'Yeleswaram' },
        ],
      },
      {
        name: 'Krishna',
        taluks: [
          { name: 'Avanigadda' },
          { name: 'Bantumilli' },
          { name: 'Bapulapadu' },
          { name: 'Challapalli' },
          { name: 'Gannavaram' },
          { name: 'Ghantasala' },
          { name: 'Gudivada' },
          { name: 'Gudlavalleru' },
          { name: 'Guduru' },
          { name: 'Kankipadu' },
          { name: 'Koduru' },
          { name: 'Kruthivennu' },
          { name: 'Machilipatnam North' },
          { name: 'Machilipatnam South' },
          { name: 'Mopidevi' },
          { name: 'Movva' },
          { name: 'Nagayalanka' },
          { name: 'Nandivada' },
          { name: 'Pamarru' },
          { name: 'Pamidimukkala' },
          { name: 'Pedana' },
          { name: 'Pedaparupudi' },
          { name: 'Penamaluru' },
          { name: 'Thotlavalluru' },
          { name: 'Unguturu' },
          { name: 'Vuyyuru' },
        ],
      },
      {
        name: 'Kurnool',
        taluks: [
          { name: 'Adoni' },
          { name: 'Adoni-2' },
          { name: 'Alur' },
          { name: 'Aspari' },
          { name: 'C.Belagal' },
          { name: 'Chippagiri' },
          { name: 'Devanakonda' },
          { name: 'Gonegandla' },
          { name: 'Gudur', pincode: '524101' },
          { name: 'Halaharvi' },
          { name: 'Holagunda' },
          { name: 'Kallur' },
          { name: 'Kodumur' },
          { name: 'Kosigi' },
          { name: 'Kowthalam' },
          { name: 'Krishnagiri' },
          { name: 'Kurnool Rural' },
          { name: 'Kurnool Urban' },
          { name: 'Maddikera (East)' },
          { name: 'Mantralayam' },
          { name: 'Nandavaram' },
          { name: 'Orvakal' },
          { name: 'Pattikonda' },
          { name: 'Pedda Kadubur' },
          { name: 'Tuggali' },
          { name: 'Veldurthy' },
          { name: 'Yemmiganur' },
        ],
      },
      {
        name: 'Markapuram',
        taluks: [
          { name: 'Ardhaveedu' },
          { name: 'Bestavaripeta' },
          { name: 'Chandra Sekhara Puram' },
          { name: 'Cumbum' },
          { name: 'Dornala' },
          { name: 'Giddalur' },
          { name: 'Hanumanthuni Padu' },
          { name: 'Kanigiri' },
          { name: 'Komarolu' },
          { name: 'Konakanamitla' },
          { name: 'Markapuram' },
          { name: 'Pamur' },
          { name: 'Pedacherlo Palle' },
          { name: 'Peddaaraveedu' },
          { name: 'Podili' },
          { name: 'Pullalacheruvu' },
          { name: 'Racherla' },
          { name: 'Tarlupadu' },
          { name: 'Tripuranthakam' },
          { name: 'Veligandla' },
          { name: 'Yerragondapalem' },
        ],
      },
      {
        name: 'Nandyal',
        taluks: [
          { name: 'Allagadda' },
          { name: 'Atmakur' },
          { name: 'Banaganapalli' },
          { name: 'Bandi Atmakur' },
          { name: 'Bethamcherla' },
          { name: 'Chagalamarri' },
          { name: 'Dhone' },
          { name: 'Dornipadu' },
          { name: 'Gadivemula' },
          { name: 'Gospadu' },
          { name: 'Jupadu Bunglow' },
          { name: 'Koilakuntla' },
          { name: 'Kolimigundla' },
          { name: 'Kothapalle' },
          { name: 'Mahanandi' },
          { name: 'Midthur' },
          { name: 'Nandikotkur' },
          { name: 'Nandyal Rural' },
          { name: 'Nandyal Urban' },
          { name: 'Owk' },
          { name: 'Pagidyala' },
          { name: 'Pamulapadu' },
          { name: 'Panyam' },
          { name: 'Peapully' },
          { name: 'Rudravaram' },
          { name: 'Sanjamala' },
          { name: 'Sirvel' },
          { name: 'Srisailam' },
          { name: 'Uyyalawada' },
          { name: 'Velugodu' },
        ],
      },
      {
        name: 'Ntr',
        taluks: [
          { name: 'Atlapragada Konduru' },
          { name: 'Chandarlapadu' },
          { name: 'Gaddamanugu Konduru' },
          { name: 'Gampalagudem' },
          { name: 'Ibrahimpatnam' },
          { name: 'Jaggaiahpeta' },
          { name: 'Kanchikacherla' },
          { name: 'Mylavaram' },
          { name: 'Nandigama' },
          { name: 'Penuganchiprolu' },
          { name: 'Reddigudem' },
          { name: 'Tiruvuru' },
          { name: 'Vatsavai' },
          { name: 'Veerullapadu' },
          { name: 'Vijayawada (Rural)' },
          { name: 'Vijayawada Central' },
          { name: 'Vijayawada East' },
          { name: 'Vijayawada North' },
          { name: 'Vijayawada West' },
          { name: 'Vissannapeta' },
        ],
      },
      {
        name: 'Palnadu',
        taluks: [
          { name: 'Amaravathi' },
          { name: 'Atchampet' },
          { name: 'Bellamkonda' },
          { name: 'Bollapalli' },
          { name: 'Chilakaluripet H/ O.Purushotha Patnam' },
          { name: 'Dachepalli' },
          { name: 'Durgi' },
          { name: 'Edlapadu' },
          { name: 'Gurajala' },
          { name: 'Ipuru' },
          { name: 'Karempudi' },
          { name: 'Krosuru' },
          { name: 'Machavaram' },
          { name: 'Macherla' },
          { name: 'Muppalla' },
          { name: 'Nadendla' },
          { name: 'Narasaraopet' },
          { name: 'Nekarikallu' },
          { name: 'Nuzendla' },
          { name: 'Pedakurapadu' },
          { name: 'Piduguralla' },
          { name: 'Rajupalem' },
          { name: 'Rentachintala' },
          { name: 'Rompicharla' },
          { name: 'Sattenapalli' },
          { name: 'Savalyapuram H/O Kanamarlapudi' },
          { name: 'Veldurthy' },
          { name: 'Vinukonda' },
        ],
      },
      {
        name: 'Parvathipuram Manyam',
        taluks: [
          { name: 'Balijipeta' },
          { name: 'Bhamini' },
          { name: 'Garugubilli' },
          { name: 'Gummalakshmipuram' },
          { name: 'Jiyyammavalasa' },
          { name: 'Komarada' },
          { name: 'Kurupam' },
          { name: 'Makkuva' },
          { name: 'Pachipenta' },
          { name: 'Palakonda' },
          { name: 'Parvathipuram' },
          { name: 'Salur' },
          { name: 'Seethampeta' },
          { name: 'Seethanagaram' },
          { name: 'Veeraghattam' },
        ],
      },
      {
        name: 'Polavaram',
        taluks: [
          { name: 'Addateegala' },
          { name: 'Chinturu' },
          { name: 'Devipatnam' },
          { name: 'Gangavaram' },
          { name: 'Gurthedu' },
          { name: 'Kunavaram' },
          { name: 'Maredumilli' },
          { name: 'Rajavommangi' },
          { name: 'Rampachodavaram' },
          { name: 'Vararamachandrapuram' },
          { name: 'Y. Ramavaram' },
          { name: 'Yetapaka' },
        ],
      },
      {
        name: 'Prakasam',
        taluks: [
          { name: 'Addanki' },
          { name: 'Ballikurava' },
          { name: 'Chimakurthy' },
          { name: 'Darsi' },
          { name: 'Donakonda' },
          { name: 'Gudluru' },
          { name: 'J.Pangulur' },
          { name: 'Kandukuru' },
          { name: 'Kondapi' },
          { name: 'Korisapadu' },
          { name: 'Kotha Patnam' },
          { name: 'Kurichedu' },
          { name: 'Lingasamudram' },
          { name: 'Maddipadu' },
          { name: 'Marripudi' },
          { name: 'Mundlamuru' },
          { name: 'Naguluppala Padu' },
          { name: 'Ongole Rural' },
          { name: 'Ongole Urban' },
          { name: 'Ponnaluru' },
          { name: 'Santhamaguluru' },
          { name: 'Santhanuthala Padu' },
          { name: 'Singarayakonda' },
          { name: 'Tangutur' },
          { name: 'Thallur' },
          { name: 'Ulavapadu' },
          { name: 'Voletivaripalem' },
          { name: 'Zarugumalli' },
        ],
      },
      {
        name: 'Sri Potti Sriramulu Nellore',
        taluks: [
          { name: 'Allur' },
          { name: 'Ananthasagaram' },
          { name: 'Anumasamudrampeta' },
          { name: 'Atmakur' },
          { name: 'Bogole' },
          { name: 'Buchireddipalem' },
          { name: 'Chejerla' },
          { name: 'Chillakur' },
          { name: 'Dagadarthi' },
          { name: 'Duttalur' },
          { name: 'Gudur', pincode: '524101' },
          { name: 'Indukurpet' },
          { name: 'Jaladanki' },
          { name: 'Kaligiri' },
          { name: 'Kaluvoya' },
          { name: 'Kavali' },
          { name: 'Kodavalur' },
          { name: 'Kondapuram' },
          { name: 'Kota' },
          { name: 'Kovur' },
          { name: 'Manubolu' },
          { name: 'Marripadu' },
          { name: 'Muthukur' },
          { name: 'Nellore Rural' },
          { name: 'Nellore Urban' },
          { name: 'Podalakur' },
          { name: 'Rapur' },
          { name: 'Sangam' },
          { name: 'Seetharamapuram' },
          { name: 'Sydapuram' },
          { name: 'Thotapalligudur' },
          { name: 'Udayagiri' },
          { name: 'Varikuntapadu' },
          { name: 'Venkatachalam' },
          { name: 'Vidavalur' },
          { name: 'Vinjamur' },
        ],
      },
      {
        name: 'Sri Sathya Sai',
        taluks: [
          { name: 'Agali' },
          { name: 'Amadagur' },
          { name: 'Amarapuram' },
          { name: 'Bathalapalli' },
          { name: 'Bukkapatnam' },
          { name: 'Chennekothapalli' },
          { name: 'Chilamathur' },
          { name: 'Dharmavaram', pincode: '515671' },
          { name: 'Gandlapenta' },
          { name: 'Gorantla' },
          { name: 'Gudibanda' },
          { name: 'Hindupur' },
          { name: 'Kadiri' },
          { name: 'Kanaganipalli' },
          { name: 'Kothacheruvu' },
          { name: 'Lepakshi' },
          { name: 'Madakasira' },
          { name: 'Mudigubba' },
          { name: 'Nallachervu' },
          { name: 'Nallamada' },
          { name: 'Nambulapulakunta' },
          { name: 'Obuladevaracheruvu' },
          { name: 'Parigi' },
          { name: 'Penukonda' },
          { name: 'Puttaparthy' },
          { name: 'Ramagiri' },
          { name: 'Roddam' },
          { name: 'Rolla' },
          { name: 'Somandepalli' },
          { name: 'Tadimarri' },
          { name: 'Talupula' },
          { name: 'Tanakal' },
        ],
      },
      {
        name: 'Srikakulam',
        taluks: [
          { name: 'Amadalavalasa' },
          { name: 'Burja' },
          { name: 'Etcherla' },
          { name: 'Ganguvarisigadam' },
          { name: 'Gara' },
          { name: 'Hiramandalam' },
          { name: 'Ichchapuram' },
          { name: 'Jalumuru' },
          { name: 'Kanchili' },
          { name: 'Kaviti' },
          { name: 'Kotabommali' },
          { name: 'Kothuru' },
          { name: 'Laveru' },
          { name: 'Laxminarasupeta' },
          { name: 'Mandasa' },
          { name: 'Meliaputti' },
          { name: 'Nandigam' },
          { name: 'Narasannapeta' },
          { name: 'Palasa' },
          { name: 'Pathapatnam' },
          { name: 'Polaki' },
          { name: 'Ponduru' },
          { name: 'Ranastalam' },
          { name: 'Santhabommali' },
          { name: 'Saravakota' },
          { name: 'Sarubujjili' },
          { name: 'Sompeta' },
          { name: 'Srikakulam' },
          { name: 'Tekkali' },
          { name: 'Vajrapukotturu' },
        ],
      },
      {
        name: 'Tirupati',
        defaultPincode: '517501',
        taluks: [
          { name: 'Balayapalli' },
          { name: 'Buchinaidu Kandriga' },
          { name: 'Chandragiri', pincode: '517101' },
          { name: 'Chinnagottigallu' },
          { name: 'Chittamur' },
          { name: 'Chitvel' },
          { name: 'Dakkili' },
          { name: 'Doravarisatram' },
          { name: 'Kodur' },
          { name: 'Kumara Venkata Bhupala Puram' },
          { name: 'Nagalapuram' },
          { name: 'Naidupet' },
          { name: 'Narayanavanam' },
          { name: 'Obulavaripalle' },
          { name: 'Ozili' },
          { name: 'Pakala' },
          { name: 'Pellakur' },
          { name: 'Penagalur' },
          { name: 'Pichatur' },
          { name: 'Pullampeta' },
          { name: 'Puttur' },
          { name: 'Ramachandrapuram' },
          { name: 'Renigunta' },
          { name: 'Satyavedu' },
          { name: 'Srikalahasti', pincode: '517644' },
          { name: 'Sullurpeta', pincode: '524121' },
          { name: 'Tada' },
          { name: 'Thottambedu' },
          { name: 'Tirupati (Rural)' },
          { name: 'Tirupati (Urban)' },
          { name: 'Vadamalapet' },
          { name: 'Vakadu' },
          { name: 'Varadaiahpalem' },
          { name: 'Venkatagiri', pincode: '524132' },
          { name: 'Yerpedu' },
          { name: 'Yerravaripalem' },
        ],
      },
      {
        name: 'Visakhapatnam',
        taluks: [
          { name: 'Anandapuram' },
          { name: 'Bheemunipatnam' },
          { name: 'Gajuwaka' },
          { name: 'Gopalapatnam' },
          { name: 'Maharanipeta' },
          { name: 'Mulagada' },
          { name: 'Padmanabham' },
          { name: 'Pedagantyada' },
          { name: 'Pendurthi' },
          { name: 'Seethammadhara' },
          { name: 'Visakhapatnam (Rural)' },
        ],
      },
      {
        name: 'Vizianagaram',
        taluks: [
          { name: 'Badangi' },
          { name: 'Bhogapuram' },
          { name: 'Bobbili' },
          { name: 'Bondapalli' },
          { name: 'Cheepurupalli' },
          { name: 'Dattirajeru' },
          { name: 'Denkada' },
          { name: 'Gajapathinagaram' },
          { name: 'Gantyada' },
          { name: 'Garividi' },
          { name: 'Gurla' },
          { name: 'Jami' },
          { name: 'Kothavalasa' },
          { name: 'Lakkavarapukota' },
          { name: 'Mentada' },
          { name: 'Merakamudidam' },
          { name: 'Nellimarla' },
          { name: 'Poosapatirega' },
          { name: 'Rajam' },
          { name: 'Ramabhadrapuram' },
          { name: 'Regidi Amadalavalasa' },
          { name: 'Santhakaviti' },
          { name: 'Srungavarapukota' },
          { name: 'Therlam' },
          { name: 'Vangara' },
          { name: 'Vepada' },
          { name: 'Vizianagaram Rural' },
          { name: 'Vizianagaram Urban' },
        ],
      },
      {
        name: 'West Godavari',
        taluks: [
          { name: 'Achanta' },
          { name: 'Akividu' },
          { name: 'Attili' },
          { name: 'Bhimavaram' },
          { name: 'Ganapavaram' },
          { name: 'Iragavaram' },
          { name: 'Kalla' },
          { name: 'Mogalthur' },
          { name: 'Narasapuram' },
          { name: 'Palacoderu' },
          { name: 'Palacole' },
          { name: 'Pentapadu' },
          { name: 'Penugonda' },
          { name: 'Penumantra' },
          { name: 'Poduru' },
          { name: 'Tadepalligudem' },
          { name: 'Tanuku' },
          { name: 'Undi' },
          { name: 'Veeravasaram' },
          { name: 'Yelamanchili' },
        ],
      },
      {
        name: 'Y.S.R. Kadapa',
        taluks: [
          { name: 'Atlur' },
          { name: 'B.Kodur' },
          { name: 'Badvel' },
          { name: 'Brahmamgarimattam' },
          { name: 'Chakrayapet' },
          { name: 'Chapad' },
          { name: 'Chennur' },
          { name: 'Chinthakommadinne' },
          { name: 'Duvvur' },
          { name: 'Gopavaram' },
          { name: 'Jammalamadugu' },
          { name: 'Kadapa' },
          { name: 'Kalasapadu' },
          { name: 'Kamalapuram' },
          { name: 'Khajipeta' },
          { name: 'Kondapuram' },
          { name: 'Lingala' },
          { name: 'Muddanur' },
          { name: 'Mylavaram' },
          { name: 'Nandalur' },
          { name: 'Peddamudiam' },
          { name: 'Pendlimarry' },
          { name: 'Porumamilla' },
          { name: 'Proddutur' },
          { name: 'Pulivendula' },
          { name: 'Rajampet', pincode: '516115' },
          { name: 'Rajupalem' },
          { name: 'S.Mydukur' },
          { name: 'Sidhout' },
          { name: 'Simhadripuram' },
          { name: 'Sri Avadhutha Kasinayana' },
          { name: 'T.Sundupalle' },
          { name: 'Thondur' },
          { name: 'Vallur' },
          { name: 'Veeraballe' },
          { name: 'Veerapunayunipalle' },
          { name: 'Vempalli' },
          { name: 'Vemula' },
          { name: 'Vontimitta' },
          { name: 'Yerraguntla' },
        ],
      },
    ],
  },
  {
    name: 'Telangana',
    code: 'TG',
    districts: [
      {
        name: 'Adilabad',
        taluks: [
          { name: 'Adilabad Rural' },
          { name: 'Adilabad Urban' },
          { name: 'Bazarhatnoor' },
          { name: 'Bela' },
          { name: 'Bheempur' },
          { name: 'Bhoraj' },
          { name: 'Boath' },
          { name: 'Gadiguda' },
          { name: 'Gudihatnoor' },
          { name: 'Ichoda' },
          { name: 'Inderavelly' },
          { name: 'Jainath' },
          { name: 'Mavala' },
          { name: 'Narnoor' },
          { name: 'Neradigonda' },
          { name: 'Sathnala' },
          { name: 'Sirikonda' },
          { name: 'Sonala' },
          { name: 'Talamadugu' },
          { name: 'Tamsi' },
          { name: 'Utnoor' },
        ],
      },
      {
        name: 'Bhadradri Kothagudem',
        taluks: [
          { name: 'Allapalli' },
          { name: 'Annapureddypalli' },
          { name: 'Aswapuram' },
          { name: 'Aswaraopeta' },
          { name: 'Bhadrachalam' },
          { name: 'Burgampahad' },
          { name: 'Chandrugonda' },
          { name: 'Cherla' },
          { name: 'Chunchupalli' },
          { name: 'Dammapeta' },
          { name: 'Dummugudem' },
          { name: 'Gundala' },
          { name: 'Julurpadu' },
          { name: 'Karakagudem' },
          { name: 'Kothagudem' },
          { name: 'Laxmidevipalli' },
          { name: 'Manuguru' },
          { name: 'Mulkalapally' },
          { name: 'Palvoncha' },
          { name: 'Pinapaka' },
          { name: 'Sujathanagar' },
          { name: 'Tekulapalli' },
          { name: 'Yellandu' },
        ],
      },
      {
        name: 'Hanumakonda',
        taluks: [
          { name: 'Athmakur' },
          { name: 'Bheemadevarpalli' },
          { name: 'Damera' },
          { name: 'Dharmasagar' },
          { name: 'Elkathurthy' },
          { name: 'Hanamkonda' },
          { name: 'Hasanparthy' },
          { name: 'Inavole' },
          { name: 'Kamalapur' },
          { name: 'Khazipet' },
          { name: 'Nadikuda' },
          { name: 'Parkal' },
          { name: 'Shayampet' },
          { name: 'Velair' },
        ],
      },
      {
        name: 'Hyderabad',
        taluks: [
          { name: 'Amberpet' },
          { name: 'Ameerpet' },
          { name: 'Asif Nagar' },
          { name: 'Bahadurpura' },
          { name: 'Bandlaguda' },
          { name: 'Charminar' },
          { name: 'Golconda' },
          { name: 'Himayatnagar' },
          { name: 'Khairatabad' },
          { name: 'Marredpally' },
          { name: 'Musheerabad' },
          { name: 'Nampally' },
          { name: 'Saidabad' },
          { name: 'Secunderabad' },
          { name: 'Shaikpet' },
          { name: 'Tirumalgiri' },
        ],
      },
      {
        name: 'Jagitial',
        taluks: [
          { name: 'Beerpur' },
          { name: 'Bheemaram (20)' },
          { name: 'Buggaram' },
          { name: 'Dharmapuri' },
          { name: 'Endapalli' },
          { name: 'Gollapalli' },
          { name: 'Ibrahimpatnam' },
          { name: 'Jagitial' },
          { name: 'Jagitial Rural' },
          { name: 'Kathlapur' },
          { name: 'Kodimial' },
          { name: 'Korutla' },
          { name: 'Mallapur' },
          { name: 'Mallial' },
          { name: 'Medipalli' },
          { name: 'Metpalli' },
          { name: 'Pegadapalli' },
          { name: 'Raikal' },
          { name: 'Sarangapur' },
          { name: 'Velgatur' },
        ],
      },
      {
        name: 'Jangoan',
        taluks: [
          { name: 'Bachannapet' },
          { name: 'Chilpur' },
          { name: 'Devaruppula' },
          { name: 'Ghanpur (Station)' },
          { name: 'Jangoan' },
          { name: 'Kodakandla' },
          { name: 'Lingalaghanpur' },
          { name: 'Narmetta' },
          { name: 'Palakurthy' },
          { name: 'Ragunathpally' },
          { name: 'Tharigoppula' },
          { name: 'Zaffergadh' },
        ],
      },
      {
        name: 'Jayashankar Bhupalapally',
        taluks: [
          { name: 'Bhupalpally' },
          { name: 'Chityal' },
          { name: 'Ghanpur (Mulug)' },
          { name: 'Kataram' },
          { name: 'Kothapallygori' },
          { name: 'Mahadevpur' },
          { name: 'Malharrao' },
          { name: 'Mogullapally' },
          { name: 'Mutharam Mahadevpur' },
          { name: 'Palimela' },
          { name: 'Regonda' },
          { name: 'Tekumatla' },
        ],
      },
      {
        name: 'Jogulamba Gadwal',
        taluks: [
          { name: 'Alampur' },
          { name: 'Dharoor' },
          { name: 'Gadwal' },
          { name: 'Ghattu' },
          { name: 'Ieeja' },
          { name: 'Itikyala' },
          { name: 'Kaloor Thimmandoddi' },
          { name: 'Maldakal' },
          { name: 'Manopad' },
          { name: 'Rajoli' },
          { name: 'Undavelly' },
          { name: 'Waddepally' },
          { name: 'Yerravalli' },
        ],
      },
      {
        name: 'Kamareddy',
        taluks: [
          { name: 'Banswada' },
          { name: 'Bhiknoor' },
          { name: 'Bibipet' },
          { name: 'Bichkunda' },
          { name: 'Birkur' },
          { name: 'Domakonda' },
          { name: 'Dongli' },
          { name: 'Gandhari' },
          { name: 'Jukkal' },
          { name: 'Kamareddy' },
          { name: 'Lingampet' },
          { name: 'Machareddy' },
          { name: 'Madnoor' },
          { name: 'Mohammadnagar' },
          { name: 'Nagireddypet' },
          { name: 'Nasurullabad' },
          { name: 'Nizamsagar' },
          { name: 'Palwancha' },
          { name: 'Pedda Kodapgal' },
          { name: 'Pitlam' },
          { name: 'Rajampet' },
          { name: 'Ramareddy' },
          { name: 'Sadashivanagar' },
          { name: 'Tadwai' },
          { name: 'Yellareddy' },
        ],
      },
      {
        name: 'Karimnagar',
        taluks: [
          { name: 'Chigurumamidi' },
          { name: 'Choppadandi' },
          { name: 'Ellandakunta' },
          { name: 'Gangadhara' },
          { name: 'Ganneruvaram' },
          { name: 'Huzurabad' },
          { name: 'Jammikunta' },
          { name: 'Karimnagar' },
          { name: 'Karimnagar Rural' },
          { name: 'Kothapally' },
          { name: 'Manakondur' },
          { name: 'Ramadugu' },
          { name: 'Shankarapatnam' },
          { name: 'Thimmapur LMD' },
          { name: 'V.Saidapur' },
          { name: 'Veenavanka' },
        ],
      },
      {
        name: 'Khammam',
        taluks: [
          { name: 'Bonakal' },
          { name: 'Chinthakani' },
          { name: 'Enkoor' },
          { name: 'Kalluru' },
          { name: 'Kamepalli' },
          { name: 'Khammam (Rural)' },
          { name: 'Khammam Urban' },
          { name: 'Konijerla' },
          { name: 'Kusumanchi' },
          { name: 'Madhira' },
          { name: 'Mudigonda' },
          { name: 'Nelakondapalli' },
          { name: 'Penuballi' },
          { name: 'Raghunadhapalem' },
          { name: 'Sathupalli' },
          { name: 'Singareni' },
          { name: 'Thallada' },
          { name: 'Tirumalayapalem' },
          { name: 'Vemsoor' },
          { name: 'Wyra' },
          { name: 'Yerrupalem' },
        ],
      },
      {
        name: 'Kumuram Bheem Asifabad',
        taluks: [
          { name: 'Asifabad' },
          { name: 'Bejjur' },
          { name: 'Chintalamanepally' },
          { name: 'Dahegoan' },
          { name: 'Jainoor' },
          { name: 'Kagaznagar' },
          { name: 'Kerameri' },
          { name: 'Koutala' },
          { name: 'Lingapur' },
          { name: 'Penchicalpet' },
          { name: 'Rebbena' },
          { name: 'Sirpur (T)' },
          { name: 'Sirpur U' },
          { name: 'Tiryani' },
          { name: 'Wankidi' },
        ],
      },
      {
        name: 'Mahabubabad',
        taluks: [
          { name: 'Bayyaram' },
          { name: 'Chinnagudur' },
          { name: 'Danthalapalle' },
          { name: 'Dornakal' },
          { name: 'Gangaram' },
          { name: 'Garla' },
          { name: 'Gudur' },
          { name: 'Inugurthy' },
          { name: 'Kesamudram' },
          { name: 'Kothaguda' },
          { name: 'Kuravi' },
          { name: 'Mahabubabad' },
          { name: 'Maripeda' },
          { name: 'Narsimhulapet' },
          { name: 'Nellikudur' },
          { name: 'Peddavangara' },
          { name: 'Seerole' },
          { name: 'Thorrur' },
        ],
      },
      {
        name: 'Mahabubnagar',
        taluks: [
          { name: 'Addakal' },
          { name: 'Balanagar' },
          { name: 'Bhoothpur' },
          { name: 'Chinnachintakunta' },
          { name: 'Devarakadra' },
          { name: 'Gandeed' },
          { name: 'Hanwada' },
          { name: 'Jadcherla' },
          { name: 'Koilkonda' },
          { name: 'Koukuntla' },
          { name: 'Mahabubnagar Rural' },
          { name: 'Mahabubnagar Urban' },
          { name: 'Midjil' },
          { name: 'Mohammadabad' },
          { name: 'Moosapet' },
          { name: 'Nawabpet' },
          { name: 'Rajapur' },
        ],
      },
      {
        name: 'Mancherial',
        taluks: [
          { name: 'Bellampally' },
          { name: 'Bheemaram' },
          { name: 'Bheemini' },
          { name: 'Chennur' },
          { name: 'Dandepally' },
          { name: 'Hajipur' },
          { name: 'Jaipur' },
          { name: 'Jannaram' },
          { name: 'Kannepally' },
          { name: 'Kasipet' },
          { name: 'Kotapally' },
          { name: 'Luxettipet' },
          { name: 'Mancherial' },
          { name: 'Mandamarri' },
          { name: 'Naspur' },
          { name: 'Nennel' },
          { name: 'Tandur' },
          { name: 'Vemanpally' },
        ],
      },
      {
        name: 'Medak',
        taluks: [
          { name: 'Alladurg' },
          { name: 'Chegunta' },
          { name: 'Chilpched' },
          { name: 'Havelighanapur' },
          { name: 'Kowdipally' },
          { name: 'Kulcharam' },
          { name: 'Manoharabad' },
          { name: 'Masaipet' },
          { name: 'Medak' },
          { name: 'Narsapur' },
          { name: 'Narsingi' },
          { name: 'Nizampet' },
          { name: 'Papannapet' },
          { name: 'Ramayampet' },
          { name: 'Regode' },
          { name: 'Shankarampet (A)' },
          { name: 'Shankarampet (R)' },
          { name: 'Shivampet' },
          { name: 'Tekmal' },
          { name: 'Toopran' },
          { name: 'Yeldurthy' },
        ],
      },
      {
        name: 'Medchal Malkajgiri',
        taluks: [
          { name: 'Alwal' },
          { name: 'Bachupally' },
          { name: 'Balanagar' },
          { name: 'Gandimaisamma Dundigal' },
          { name: 'Ghatkesar' },
          { name: 'Kapra' },
          { name: 'Keesara' },
          { name: 'Kukatpally' },
          { name: 'Malkajgiri' },
          { name: 'Medchal' },
          { name: 'Medipally' },
          { name: 'Muduchinthalapally' },
          { name: 'Qutballapur' },
          { name: 'Shamirpet' },
          { name: 'Uppal' },
        ],
      },
      {
        name: 'Mulugu',
        taluks: [
          { name: 'Eturunagaram' },
          { name: 'Govindaraopet' },
          { name: 'Kannaigudem' },
          { name: 'Mallampally' },
          { name: 'Mangapet' },
          { name: 'Mulug' },
          { name: 'Tadvai' },
          { name: 'Venkatapur' },
          { name: 'Venkatapuram' },
          { name: 'Wajedu' },
        ],
      },
      {
        name: 'Nagarkurnool',
        taluks: [
          { name: 'Achampet' },
          { name: 'Amrabad' },
          { name: 'Balmoor' },
          { name: 'Bijinapally' },
          { name: 'Charakonda' },
          { name: 'Kalwakurthy' },
          { name: 'Kodair' },
          { name: 'Kollapur' },
          { name: 'Lingal' },
          { name: 'Nagarkurnool' },
          { name: 'Padara' },
          { name: 'Peddakothapally' },
          { name: 'Pentlavelli' },
          { name: 'Tadoor' },
          { name: 'Telkapally' },
          { name: 'Thimmajipet' },
          { name: 'Uppununthala' },
          { name: 'Urkonda' },
          { name: 'Vangoor' },
          { name: 'Veldanda' },
        ],
      },
      {
        name: 'Nalgonda',
        taluks: [
          { name: 'Adavidevulapalli' },
          { name: 'Anumula' },
          { name: 'Chandampeta' },
          { name: 'Chandur' },
          { name: 'Chinthapally' },
          { name: 'Chityal' },
          { name: 'Dameracherla' },
          { name: 'Devarakonda' },
          { name: 'Gattuppal' },
          { name: 'Gudipally' },
          { name: 'Gundlapally' },
          { name: 'Gurrampode' },
          { name: 'Kanagal' },
          { name: 'Kattangur' },
          { name: 'Kethepally' },
          { name: 'Kondamallepally' },
          { name: 'Madugulapally' },
          { name: 'Marriguda' },
          { name: 'Miryalaguda' },
          { name: 'Munugode' },
          { name: 'Nakrekal' },
          { name: 'Nalgonda' },
          { name: 'Nampally' },
          { name: 'Narketpally' },
          { name: 'Neredugommu' },
          { name: 'Nidmanoor' },
          { name: 'Pedda Adesherlapally' },
          { name: 'Peddavoora' },
          { name: 'Shaligouraram' },
          { name: 'Thipparthy' },
          { name: 'Tirumalagiri Sagar' },
          { name: 'Tripuraram' },
          { name: 'Vemulapally' },
        ],
      },
      {
        name: 'Narayanpet',
        taluks: [
          { name: 'Damargidda' },
          { name: 'Dhanwada' },
          { name: 'Gundumal' },
          { name: 'Kosgi' },
          { name: 'Kothapally (15)' },
          { name: 'Krishna' },
          { name: 'Maddur' },
          { name: 'Maganoor' },
          { name: 'Makthal' },
          { name: 'Marikal' },
          { name: 'Narayanpet' },
          { name: 'Narwa' },
          { name: 'Utkoor' },
        ],
      },
      {
        name: 'Nirmal',
        taluks: [
          { name: 'Basar' },
          { name: 'Bhainsa' },
          { name: 'Dasturabad' },
          { name: 'Dilawarpur' },
          { name: 'Kaddam Peddur' },
          { name: 'Khanapur' },
          { name: 'Kubeer' },
          { name: 'Kuntala' },
          { name: 'Laxmanchanda' },
          { name: 'Lokeswaram' },
          { name: 'Mamada' },
          { name: 'Mudhole' },
          { name: 'Narsapur G' },
          { name: 'Nirmal Rural' },
          { name: 'Nirmal U' },
          { name: 'Pembi' },
          { name: 'Sarangapur' },
          { name: 'Soan' },
          { name: 'Tanoor' },
        ],
      },
      {
        name: 'Nizamabad',
        taluks: [
          { name: 'Aloor' },
          { name: 'Armoor' },
          { name: 'Balkonda' },
          { name: 'Bheemgal' },
          { name: 'Bodhan' },
          { name: 'Chandur' },
          { name: 'Dharpally' },
          { name: 'Dichpally' },
          { name: 'Donkeshwar' },
          { name: 'Indalwai' },
          { name: 'Jakranpally' },
          { name: 'Kammarpally' },
          { name: 'Kotagiri' },
          { name: 'Makloor' },
          { name: 'Mendora' },
          { name: 'Morthad' },
          { name: 'Mosara' },
          { name: 'Mugpal' },
          { name: 'Mupkal' },
          { name: 'Nandipet' },
          { name: 'Navipet' },
          { name: 'Nizamabad North' },
          { name: 'Nizamabad Rural' },
          { name: 'Nizamabad South' },
          { name: 'Pothangal' },
          { name: 'Renjal' },
          { name: 'Rudrur' },
          { name: 'Saloora' },
          { name: 'Sirikonda' },
          { name: 'Vailpoor' },
          { name: 'Varni' },
          { name: 'Yedapally' },
          { name: 'Yergatla' },
        ],
      },
      {
        name: 'Peddapalli',
        taluks: [
          { name: 'Anthergaon' },
          { name: 'Dharmaram' },
          { name: 'Eligaid' },
          { name: 'Julapalli' },
          { name: 'Kamanpur' },
          { name: 'Manthani' },
          { name: 'Mutharam (Manthani)' },
          { name: 'Odela' },
          { name: 'Palakurthy' },
          { name: 'Peddapalli' },
          { name: 'Ramagiri' },
          { name: 'Ramagundam' },
          { name: 'Srirampur' },
          { name: 'Sulthanabad' },
        ],
      },
      {
        name: 'Rajanna Sircilla',
        taluks: [
          { name: 'Boinpalli' },
          { name: 'Chandurthi' },
          { name: 'Gambhiraopet' },
          { name: 'Illanthakunta' },
          { name: 'Konaraopet' },
          { name: 'Mustabad' },
          { name: 'Rudrangi' },
          { name: 'Sircilla' },
          { name: 'Thangallapalli' },
          { name: 'Veernapalli' },
          { name: 'Vemulawada' },
          { name: 'Vemulawada Rural' },
          { name: 'Yellareddipet' },
        ],
      },
      {
        name: 'Ranga Reddy',
        taluks: [
          { name: 'Abdullapurmet' },
          { name: 'Amangal' },
          { name: 'Balapur' },
          { name: 'Chevella' },
          { name: 'Farooqnagar' },
          { name: 'Gandipet' },
          { name: 'Hayathnagar' },
          { name: 'Ibrahimpatnam' },
          { name: 'Jilled Chowdergudem' },
          { name: 'Kadthal' },
          { name: 'Kandukur' },
          { name: 'Keshampet' },
          { name: 'Kondurg' },
          { name: 'Kothur' },
          { name: 'Madgul' },
          { name: 'Maheshwaram' },
          { name: 'Manchal' },
          { name: 'Moinabad' },
          { name: 'Nandigama' },
          { name: 'Rajendranagar' },
          { name: 'Saroornagar' },
          { name: 'Serilingampally' },
          { name: 'Shabad' },
          { name: 'Shamshabad' },
          { name: 'Shankarpalle' },
          { name: 'Thalakondapally' },
          { name: 'Yacharam' },
        ],
      },
      {
        name: 'Sangareddy',
        taluks: [
          { name: 'Ameenpur' },
          { name: 'Andole' },
          { name: 'Chowtakur' },
          { name: 'Gummadidala' },
          { name: 'Hathnoora' },
          { name: 'Jharasangam' },
          { name: 'Jinnaram' },
          { name: 'Kalher' },
          { name: 'Kandi' },
          { name: 'Kangti' },
          { name: 'Kohir' },
          { name: 'Kondapur' },
          { name: 'Manoor' },
          { name: 'Mogudampally' },
          { name: 'Munipally' },
          { name: 'Nagalgidda' },
          { name: 'Narayankhed' },
          { name: 'Nizampet (28)' },
          { name: 'Nyalkal' },
          { name: 'Patancheru' },
          { name: 'Pulkal' },
          { name: 'Raikode' },
          { name: 'Ramchandrapuram' },
          { name: 'Sadasivpet' },
          { name: 'Sangareddy' },
          { name: 'Sirgapoor' },
          { name: 'Vatpally' },
          { name: 'Zahirabad' },
        ],
      },
      {
        name: 'Siddipet',
        taluks: [
          { name: 'Akberpet-Bhoompally' },
          { name: 'Akkannapet' },
          { name: 'Bejjanki' },
          { name: 'Cherial' },
          { name: 'Chinnakodur' },
          { name: 'Dhoolmitta' },
          { name: 'Doultabad' },
          { name: 'Dubbak' },
          { name: 'Gajwel' },
          { name: 'Husnabad' },
          { name: 'Jagdevpur' },
          { name: 'Koheda' },
          { name: 'Komuravelli' },
          { name: 'Kondapak' },
          { name: 'Kukunoorpally' },
          { name: 'Maddur' },
          { name: 'Markook' },
          { name: 'Mirdoddi' },
          { name: 'Mulug' },
          { name: 'Nangnoor' },
          { name: 'Narayanaraopet' },
          { name: 'Raipole' },
          { name: 'Siddipet Rural' },
          { name: 'Siddipet Urban' },
          { name: 'Thoguta' },
          { name: 'Wargal' },
        ],
      },
      {
        name: 'Suryapet',
        taluks: [
          { name: 'Ananthagiri' },
          { name: 'Atmakur (S)' },
          { name: 'Chilkur' },
          { name: 'Chinthalapalem' },
          { name: 'Chivemla' },
          { name: 'Garidepally' },
          { name: 'Huzurnagar' },
          { name: 'Jajireddygudem' },
          { name: 'Kodad' },
          { name: 'Maddirala' },
          { name: 'Mattampally' },
          { name: 'Mellachervu' },
          { name: 'Mothey' },
          { name: 'Munagala' },
          { name: 'Nadigudem' },
          { name: 'Nagaram' },
          { name: 'Nereducherla' },
          { name: 'Nuthanakal' },
          { name: 'Palakeedu' },
          { name: 'Penpahad' },
          { name: 'Suryapet' },
          { name: 'Thirumalagiri' },
          { name: 'Thungaturthy' },
        ],
      },
      {
        name: 'Vikarabad',
        taluks: [
          { name: 'Bantwaram' },
          { name: 'Basheerabad' },
          { name: 'Bomaraspeta' },
          { name: 'Chowdapur' },
          { name: 'Dharur' },
          { name: 'Doma' },
          { name: 'Doulathabad' },
          { name: 'Dudyal' },
          { name: 'Kodangal' },
          { name: 'Kotepally' },
          { name: 'Kulkacharla' },
          { name: 'Marpalle' },
          { name: 'Mominpet' },
          { name: 'Nawabpet' },
          { name: 'Pargi' },
          { name: 'Peddemul' },
          { name: 'Pudur' },
          { name: 'Tandur' },
          { name: 'Vikarabad' },
          { name: 'Yelal' },
        ],
      },
      {
        name: 'Wanaparthy',
        taluks: [
          { name: 'Amarchintha' },
          { name: 'Atmakur' },
          { name: 'Chinnambavi' },
          { name: 'Ghanpur' },
          { name: 'Gopalpeta' },
          { name: 'Kothakota' },
          { name: 'Madanapur' },
          { name: 'Pangal' },
          { name: 'Pebbair' },
          { name: 'Peddamandadi' },
          { name: 'Revally' },
          { name: 'Srirangapur' },
          { name: 'Wanaparthy' },
          { name: 'Weepangandla' },
          { name: 'Yedula' },
        ],
      },
      {
        name: 'Warangal',
        taluks: [
          { name: 'Chennaraopet' },
          { name: 'Duggondi' },
          { name: 'Geesugonda' },
          { name: 'Khanapur' },
          { name: 'Khila Warangal' },
          { name: 'Nallabelli' },
          { name: 'Narsampet' },
          { name: 'Nekkonda' },
          { name: 'Parvathagiri' },
          { name: 'Rayaparthy' },
          { name: 'Sangem' },
          { name: 'Warangal' },
          { name: 'Wardhannapet' },
        ],
      },
      {
        name: 'Yadadri Bhuvanagiri',
        taluks: [
          { name: 'Adda Guduru' },
          { name: 'Alair' },
          { name: 'Atmakur (M)' },
          { name: 'B Pochampally' },
          { name: 'Bhongir' },
          { name: 'Bibinagar' },
          { name: 'Bommalaramaram' },
          { name: 'Choutuppal' },
          { name: 'Gundala' },
          { name: 'Motakonduru' },
          { name: 'Mothkur' },
          { name: 'Narayanpur' },
          { name: 'Rajapeta' },
          { name: 'Ramannapet' },
          { name: 'Thurkapally' },
          { name: 'Valigonda' },
          { name: 'Yadagirigutta' },
        ],
      },
    ],
  },
  {
    name: 'Kerala',
    code: 'KL',
    districts: [
      {
        name: 'Palakkad',
        defaultPincode: '678001',
        taluks: [
          { name: 'Palakkad', pincode: '678001' },
          { name: 'Chittur', pincode: '678101' },
          { name: 'Alathur', pincode: '678541' },
          { name: 'Ottappalam', pincode: '679101' },
          { name: 'Mannarkkad', pincode: '678582' },
          { name: 'Pattambi', pincode: '679303' },
        ],
      },
      {
        name: 'Wayanad',
        defaultPincode: '673121',
        taluks: [
          { name: 'Vythiri', pincode: '673576' },
          { name: 'Sulthan Bathery', pincode: '673592' },
          { name: 'Mananthavady', pincode: '670645' },
        ],
      },
      {
        name: 'Idukki',
        defaultPincode: '685603',
        taluks: [
          { name: 'Devikulam', pincode: '685613' },
          { name: 'Udumbanchola', pincode: '685554' },
          { name: 'Thodupuzha', pincode: '685584' },
          { name: 'Peermade', pincode: '685531' },
        ],
      },
    ],
  },
];

function findState(stateName: string): StateInfo | undefined {
  return STATES_DATA.find((s) => s.name.toLowerCase() === (stateName || '').toLowerCase());
}

function findDistrict(stateName: string, districtName: string): DistrictInfo | undefined {
  const st = findState(stateName);
  if (!st) return undefined;
  // Older spellings on saved records (e.g. "Tiruvallur") resolve to the directory name
  const target = canonicalDistrictKey(districtName);
  return st.districts.find((d) => d.name.toLowerCase() === target);
}

/**
 * Returns all state names.
 */
export function getStates(): string[] {
  return STATES_DATA.map((s) => s.name);
}

/**
 * Returns all districts for a given state name.
 */
export function getDistricts(stateName: string): string[] {
  const st = findState(stateName);
  return st ? st.districts.map((d) => d.name) : [];
}

/**
 * Returns the canonical district name for a possibly-aliased spelling, or undefined if unknown.
 */
export function canonicalDistrict(stateName: string, districtName: string): string | undefined {
  return findDistrict(stateName, districtName)?.name;
}

/**
 * Returns all talukas for a given state and district.
 */
export function getTaluks(stateName: string, districtName: string): TalukInfo[] {
  return findDistrict(stateName, districtName)?.taluks ?? [];
}

/**
 * Finds suggested pincode for a given state, district, and taluk.
 */
export function getSuggestedPincode(stateName: string, districtName: string, talukName: string): string | undefined {
  const dist = findDistrict(stateName, districtName);
  if (!dist) return undefined;
  const taluk = dist.taluks.find((t) => t.name.toLowerCase() === (talukName || '').toLowerCase());
  return taluk?.pincode || dist.defaultPincode;
}

type VillageIndex = Record<string, Record<string, string[]>>;

const VILLAGE_LOADERS: Record<string, () => Promise<{ default: unknown }>> = {
  'tamil nadu': () => import('./tn-villages.json'),
  'andhra pradesh': () => import('./ap-villages.json'),
  telangana: () => import('./tg-villages.json'),
};
const villageCache = new Map<string, Promise<VillageIndex>>();

function loadVillageIndex(stateKey: string): Promise<VillageIndex> | undefined {
  const loader = VILLAGE_LOADERS[stateKey];
  if (!loader) return undefined;
  let pending = villageCache.get(stateKey);
  if (!pending) {
    pending = loader()
      .then((m) => m.default as VillageIndex)
      .catch((err) => {
        villageCache.delete(stateKey); // allow a retry after a failed chunk load
        throw err;
      });
    villageCache.set(stateKey, pending);
  }
  return pending;
}

/**
 * Returns villages for a state/district/taluk. States without village data resolve to an empty list.
 */
export async function getVillages(stateName: string, districtName: string, talukName: string): Promise<string[]> {
  const dist = findDistrict(stateName, districtName);
  if (!dist || !talukName) return [];
  const index = loadVillageIndex((stateName || '').toLowerCase());
  if (!index) return [];
  const byTaluk = (await index)[dist.name] ?? {};
  const key = Object.keys(byTaluk).find((t) => t.toLowerCase() === talukName.toLowerCase());
  return key ? byTaluk[key] : [];
}
